### ISSUE TITLE
Create state for each component

### ISSUE THREAD

**Issue by Haroonabdulrazaq** [Haroonabdulrazaq/World-Clock#2]
- [ ] State should reside in the container that consists of time input, date picker and submit button
- [ ]  create a state for -ve time zone
- [ ]  create a state for +ve time zone
- [ ] Each time zone should consist of digital time and date

**Comment by yonis9** [comment]
Hi, can you give me more details about the app, what should it do and what is the state logic?

**Comment by Haroonabdulrazaq** [comment]
Hi, who is this please

**Comment by Haroonabdulrazaq** [comment]
Sorry to ask that, from Github right? The app is aimed at improving remote
collaboration between developers..Let assume you have 3-4 partner that are
in a different time zone..The app will allow you to choose the best meeting
time for your partners because you can view their time. If you have any
more question you can ask, Or if you want to contribute let me know. I am
using React and avoiding Redux.
